repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--"]
        require_serial: true
      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
        require_serial: true
      - id: clippy-workaround
        name: clippy-workaround
        entry: bash -c "find . -name *.rs | xargs touch"
        language: system
        always_run: true
        pass_filenames: false
        require_serial: true
      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        args: ["--", "-A", "dead-code", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
        require_serial: true

