fail_fast: true
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo
        language: system
        types: [rust]
        args: ["fmt", "--"]
        require_serial: true
      - id: cargo-check
        name: cargo check
        entry: cargo
        language: system
        args: ["check"]
        types: [rust]
        pass_filenames: false
        require_serial: true
      - id: clippy-workaround
        name: clippy workaround
        entry: bash
        args: ["-c", "find ./*blkcapt* -name '*.rs' | xargs touch"]
        language: system
        always_run: true
        pass_filenames: false
        require_serial: true
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo
        language: system
        args: ["clippy", "--", "-A", "dead-code", "-D", "clippy::unwrap_used", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
        require_serial: true

