[package]
name = "blkcaptwrk"
version = "0.1.0"
authors = ["opensource@rebeagle.com"]
edition = "2018"

[dependencies]
libblkcapt = { path = "../libblkcapt" }
anyhow = "1.0.31"
thiserror = "1.0.20"
log = "0.4"
pretty_env_logger = "0.4"
human-panic = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
